#! /bin/bash


#specy:  an Arch Linux system command line description tool

#Copyright (C) 2014  Max Weis


#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.


if ! [ -f "$HOME/.local/share/specy/config" ]; then

        echo Your GPU model:  
        read gpu
        echo $gpu >> ~/.local/share/specy/config
        echo 

        #echo Your primary drive partition:  
        #read drive
        #echo $drive >> ~/.local/share/specy/config
        #echo

        echo Your preferred text editor:  
        read editor
        echo $editor >> ~/.local/share/specy/config
fi

mkdir ~/.local/share/specy -p
cp $(pwd)/{ram.py,drive.py} ~/.local/share/specy 
